version: 2.1
orbs:
  node: circleci/node@2.0.0
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    executor:
      name: node/default
    steps:
      - checkout
      - node/test:
          steps:
            - run:
                name: Lint files
                command: yarn lint

            - run:
                name: Check types
                command: yarn tsc

            - run:
                name: Run tests
                command: yarn test
workflows:
    build-and-test:
      jobs:
        - build-and-test