version: 2.1
orbs:
  node: circleci/node@2.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '10.17.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - run:
          name: Install deps
          command: yarn

      - run:
          name: Lint files
          command: yarn lint

      - run:
          name: Check types
          command: yarn tsc

      - run:
          name: Run tests
          command: yarn test
workflows:
    build-and-test:
      jobs:
        - build-and-test