version: 2.1
orbs:
  node: circleci/node@2.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: "10.17.0"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - run:
          name: Install deps
          command: yarn

      - run:
          name: Lint files
          command: yarn lint

      - run:
          name: Check types
          command: yarn tsc

      - run:
          name: Run tests
          command: yarn test

  deploy-staging:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Add remote git
          command: git remote add staging dokku@cueup.io:staging.cueup
      - run:
          name: Deploy
          command: git push staging master

  deploy-production:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Add remote git
          command: git remote add production dokku@cueup.io:cueup
      - run:
          name: Deploy
          command: git push production master

workflows:
  build-deploy:
    jobs:
      - build-and-test
      - deploy-staging:
          requires:
            - build-and-test
          filters:
            branches:
              only: staging
      - deploy-production:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
