version: 2.1
orbs:
  node: circleci/node@2.0.0
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install deps
          command: yarn

      - run:
          name: Lint files
          command: yarn lint

      - run:
          name: Check types
          command: yarn tsc

      - run:
          name: Run tests
          command: yarn test
workflows:
    build-and-test:
      jobs:
        - build-and-test