declare const styles: {
    readonly 'blink': string;
    readonly 'book-dj-location': string;
    readonly 'breadcrumbs': string;
    readonly 'card': string;
    readonly 'city-illustration': string;
    readonly 'col-md-6': string;
    readonly 'container': string;
    readonly 'content': string;
    readonly 'event-submit-wrapper': string;
    readonly 'fix-top-mobile': string;
    readonly 'gm-style': string;
    readonly 'location-page': string;
    readonly 'locations-page': string;
    readonly 'menu-wrapper': string;
    readonly 'request-form': string;
    readonly 'row': string;
    readonly 'show-tablet-down': string;
    readonly 'span-wrapper': string;
    readonly 'thank-you-text': string;
    readonly 'window-lights': string;
};
export = styles;
