declare const styles: {
    readonly 'author-link': string;
    readonly 'blog': string;
    readonly 'blog-post': string;
    readonly 'card': string;
    readonly 'container': string;
    readonly 'img-wrapper': string;
    readonly 'newsletter-signup': string;
    readonly 'popup': string;
    readonly 'post-card-excerpt': string;
    readonly 'post-content': string;
    readonly 'post-feed': string;
    readonly 'post-preview': string;
    readonly 'signup': string;
    readonly 'social-signup': string;
    readonly 'subscribe-newsletter': string;
    readonly 'text-field': string;
    readonly 'title': string;
};
export = styles;
