declare const styles: {
    readonly 'noUi-background': string;
    readonly 'noUi-base': string;
    readonly 'noUi-connect': string;
    readonly 'noUi-draggable': string;
    readonly 'noUi-extended': string;
    readonly 'noUi-handle': string;
    readonly 'noUi-horizontal': string;
    readonly 'noUi-origin': string;
    readonly 'noUi-stacking': string;
    readonly 'noUi-state-drag': string;
    readonly 'noUi-state-tap': string;
    readonly 'noUi-target': string;
    readonly 'noUi-vertical': string;
    readonly 'rc-slider': string;
    readonly 'rc-slider-disabled': string;
    readonly 'rc-slider-handle': string;
    readonly 'rc-slider-rail': string;
    readonly 'rc-slider-track': string;
    readonly 'slider': string;
};
export = styles;
